[package]
name = "lancea-provider-emoji"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lancea-model = { path = "../model" }
